### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Inktheidiot9** [faizul726/matject#1]
I crash when i open inventory.

**Comment by faizul726** [comment]
@Inktheidiot9 can you explain better?

**Comment by Inktheidiot9** [comment]
heres a video about the issue
https://youtu.be/efMTRNd6LBA

**Comment by faizul726** [comment]
it's probably something wrong with the shader. i suggest you to try full restore of `restoreVanillaShaders.bat` to restore original ones first then try the shader again

**Comment by Inktheidiot9** [comment]
I used the full restore, after the procedure, I opened minecraft and it crashed on me after I tried to play a world. before the world could load fully.

**Comment by faizul726** [comment]
> I used the full restore, after the procedure, I opened minecraft and it crashed on me after I tried to play a world. before the world could load fully.

i see. the most possible cause could be something got broken during the injection. and there was a small problem in restoring that i fixed in last update

what you can do?
- reinstall minecraft using adguard store appx
- or i will give my 1.21.30 backup that you can restore for now.

btw, they released 1.21.31 recently. if you haven't updated the game yet, you can update it. it will automatically reinstall all the modified files

**Comment by faizul726** [comment]
Closing #1 because of inactivity
