### ISSUE TITLE
Cannot unlock folder

### ISSUE THREAD

**Issue by mitolovesyou** [faizul726/matject#3]
SOLVED
in short, the bat file thinks WindowsApps folder is locked when its unlocked
i know my way with computers, i actually already have important locked folders already unlocked. 
regardless i still proceeded with the basic given instructions.
when proceeding with the bat file, it asks if i want to unlock the already unlocked WindowsApps folder.
i proceeded knowing that whoever coded this likely didn't take this into consideration.
anywho, the bat file simply failed when attempting to unlock the already unlocked folder.
i thought that maybe having the folder unlocked prior potentially broke the process.
so i locked the folder gave it a try but to no avail.
even using IOBit manually to unlock the folder still didn't work.
thus i sit here writing this issue
please fix / aid me on my situation :)

(i've already reassured that IOBit was installed in the right directory)
thanks

UPDATE:
fixed it my self. i forgot to run it as admin, im so silly XD
dont forget to run the bat file as admin people!!

**Comment by faizul726** [comment]
I didn't implement anything that checks if WindowsApps is already unlocked.

Here the term `unlocking` is a bit misleading. It means taking ownership of `C:\Program Files\WindowsApps` folder so that it can read the folder content for making backup.

I will probably change the word later. As well as adding some kind of check.
